name: Rust CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1  # Remplacez v1 par la version que vous souhaitez utiliser
      with:
        profile: minimal
        toolchain: stable


    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

    - name: Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: cargo build --release --verbose
