name: commit_check

on: push

jobs:
  convention_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check Commit Message
        run: |
          if ! git log -1 --pretty=%B | grep -E "^\[(\+|-|\*|>|!|\^|@|%|#)\]" ; then
            echo "Commit message must include one of the conventional types."
            exit 1
          fi
